config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'shortcodes#index', as: 'home'

  resources :shortcodes

  get '/top100', to: 'shortcodes#top100', as: 'top100'
  post '/short_url/:original_url', to: 'shortcodes#create', as: 'original_url'
  get '/:short_url', to: 'shortcodes#goto', as: 'goto'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortcode.rb
require 'uri'

class Shortcode < ApplicationRecord
    validates :original_url, presence: true,
                             uniqueness: {scope: :original_url, message: "Entry already exists"}

    CHAR_MAP = [*'a'..'z', *'A'..'Z', *'0'..'9'].freeze

    def get_short_url
        shortcode = ""
        if self[:original_url].present?
            x = self[:original_url].length * rand(128...254)
            puts x
            while x > 0
                shortcode = shortcode + CHAR_MAP[x%62]
                x = x/62
            end
        end
        self[:short_url] = shortcode
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  protect_from_forgery with: :null_session

  def initialize
    @logger
  end

  def index
    render "login"
  end

  def create
    @logger = [params[:un_form], params[:pw_form]].join(":")
    puts "[DEBUG] un:pw -> " + @logger
    render 'logged_in'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User
             .find_by(email: params["un_form"])
             .try(:authenticate, params["pw_form"])

    if user
      session[:user_id] = user.id
      render json: {
        status: :created,
        logged_in: true,
        user: user
      }
    else
      render json: { status: 401 }
    end
  end
  def logged_in
    if @current_user
      render json: {
        logged_in: true,
        user: @current_user
      }
    else
      render json: {
        logged_in: false
      }
    end
  end

  def logout
    reset_session
    render json: { status: 200, logged_out: true }
  end
end

app/controllers/shortcodes_controller.rb
class ShortcodesController < ApplicationController
    protect_from_forgery with: :null_session
    http_basic_authenticate_with :name => "admin", :password => "password"

    def index
        @shortcodes = Shortcode.all.order('popularity DESC')
        render 'index'
    end

    def top100
        @shortcodes = Shortcode.all.order('popularity DESC').limit(100)
        render 'index'
    end

    def show
        @shortcode = Shortcode.find(params[:id])
        render 'show'
    end

    def goto
        @shortcode = Shortcode.find_by(short_url: params[:short_url])
        if @shortcode != nil
            @shortcode.increment!(:popularity,1)
            if @shortcode.save
                redirect_to @shortcode.original_url
            else
                render json: 'problem loading page'
            end
        else
            redirect_to '/'
        end
    end

    def new
        @shortcode = Shortcode.new
    end

    def create
        @shortcode = Shortcode.new
        @shortcode.original_url = params[:shortcode][:original_url]
        @shortcode.get_short_url
        @shortcode.popularity = 1
        if @shortcode.save
            UpdateTitleJob.perform_later @shortcode.id
            redirect_to '/'
        else
            render 'new'
        end
    end

    private def shortcode_params
        params.permit(:original_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortcodes_helper.rb
module ShortcodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">URL Shortcode Generator</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item nav-link">
          <%= link_to "Home", home_path %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to "New", new_shortcode_path %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/login/logged_in.html.erb
<h1>Logged in...</h1>

<script>console.log("[DEBUG] <%= @logger %>")</script>

app/views/login/login.html.erb
<h1>URL Shortcode Generator</h1>
<h2>Top Shortcodes</h2>
<form name="login_form" method="post" action="/sessions">
  <input type="text" value="Username" name="un_form">
  <input type="text" value="Password" name="pw_form">
  <input type="submit" value="Login" name="login_button">
</form>

app/views/shortcodes/index.html.erb
<h1>URL Shortcode Generator</h1>
<h2>Top Shortcodes</h2>
<% @shortcodes.each do |shortcode| %>
    <div class="card card-body bg-light">
        <p>Original: <%= shortcode.original_url.html_safe %></p>
        <p>Shortcode: <%= link_to shortcode.short_url, goto_path(shortcode.short_url) %></p>
        <p>Popularity: <%= shortcode.popularity %></p>
    </div><br>
<% end %>

app/views/shortcodes/new.html.erb
<h1>New shortcode</h1>
<%= form_for :shortcode, url: shortcodes_path, method: :post do |f| %>
    <% if @shortcode.errors.any? %>
        <% @shortcode.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :original_url %><br>
        <%= f.text_field(:original_url, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/shortcodes/show.html.erb
<br><br><br>
<div class="card card-body bg-light">
    <p>Original: <%= @shortcode.original_url %></p>
    <p>Shortcode: <%= @shortcode.short_url %></p>
    <p>Popularity: <%= @shortcode.popularity %></p>
</div><br>